# =============================================================
#                  S3 LOG DESTINATION BUCKET
# =============================================================
#
# Stores S3 server access logs generated by the temporary
# Ansible/SSM transfer bucket.
#
# This bucket contains infrastructure logs only.
#
# It is kept separate from the transfer bucket because an S3
# bucket should not send its access logs back into itself.
# =============================================================

resource "aws_s3_bucket" "log_bucket" {
  # checkov:skip=CKV2_AWS_62:This bucket only stores S3 server access logs and has no event-driven consumer.
  # checkov:skip=CKV_AWS_144:Cross-region replication is unnecessary for this disposable single-region environment.
  # checkov:skip=CKV_AWS_145:S3 server access log destination uses SSE-S3 instead of a customer-managed KMS key.
  # checkov:skip=CKV_AWS_21:Versioning is unnecessary for temporary append-only access logs that are lifecycle-managed.

  bucket = "logbeacon-log-bucket"

  # The bucket contains only temporary infrastructure logs.
  #
  # During `terraform destroy`, Terraform is allowed to delete
  # all remaining objects before deleting the bucket itself.
  force_destroy = true

  tags = merge(
    local.common_tags,
    {
      Name = "logbeacon-log-bucket"
    }
  )
}


# =============================================================
#              LOG BUCKET PUBLIC ACCESS BLOCK
# =============================================================
#
# The logging bucket must never be publicly accessible.
#
# The S3 logging service receives permission through the
# bucket policy below. The bucket itself does not need to
# be public.
# =============================================================

resource "aws_s3_bucket_public_access_block" "log_bucket" {
  bucket = aws_s3_bucket.log_bucket.id

  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}


# =============================================================
#                LOG BUCKET ENCRYPTION
# =============================================================
#
# S3 server access logging uses SSE-S3 encryption for the
# destination bucket.
#
# AES256 means encryption is handled using an S3-managed key.
# =============================================================

resource "aws_s3_bucket_server_side_encryption_configuration" "log_bucket" {
  bucket = aws_s3_bucket.log_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}


# =============================================================
#                 LOG BUCKET LIFECYCLE
# =============================================================
#
# Access logs are useful temporarily for auditing/debugging,
# but this project does not need to retain them indefinitely.
#
# Logs older than 7 days are automatically deleted.
#
# Incomplete multipart uploads are also removed after 1 day.
# =============================================================

resource "aws_s3_bucket_lifecycle_configuration" "log_bucket" {
  bucket = aws_s3_bucket.log_bucket.id

  rule {
    id     = "expire-access-logs"
    status = "Enabled"

    # Empty filter means this lifecycle rule applies
    # to every object stored in the bucket.
    filter {}

    # Remove server access logs after 7 days.
    expiration {
      days = 7
    }

    # Remove abandoned multipart uploads.
    abort_incomplete_multipart_upload {
      days_after_initiation = 1
    }
  }
}


# =============================================================
#                S3 LOGGING BUCKET POLICY
# =============================================================
#
# S3 server access logs are delivered by:
#
#   logging.s3.amazonaws.com
#
# This policy allows the S3 logging service to write objects
# into:
#
#   s3://logbeacon-log-bucket/
#       ansible-ssm-transfer-logs/
#
# The SourceArn and SourceAccount conditions prevent unrelated
# S3 buckets/accounts from writing logs into this bucket.
# =============================================================

data "aws_iam_policy_document" "logging_bucket_policy" {
  statement {
    sid    = "AllowS3ServerAccessLogs"
    effect = "Allow"

    principals {
      type = "Service"

      identifiers = [
        "logging.s3.amazonaws.com"
      ]
    }

    actions = [
      "s3:PutObject"
    ]

    # S3 logging may write only under this prefix.
    resources = [
      "${aws_s3_bucket.log_bucket.arn}/ansible-ssm-transfer-logs/*"
    ]

    # Only server access logs generated from our transfer
    # bucket are allowed.
    condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"

      values = [
        aws_s3_bucket.ansible_ssm_transfer.arn
      ]
    }

    # The source bucket must belong to this AWS account.
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"

      values = [
        data.aws_caller_identity.current.account_id
      ]
    }
  }
}


# =============================================================
#              ATTACH LOG BUCKET POLICY
# =============================================================
#
# Attaches the policy defined above to the destination
# logging bucket.
# =============================================================

resource "aws_s3_bucket_policy" "log_bucket_policy" {
  bucket = aws_s3_bucket.log_bucket.id
  policy = data.aws_iam_policy_document.logging_bucket_policy.json
}


# =============================================================
#                ANSIBLE / SSM TRANSFER BUCKET
# =============================================================
#
# Temporary bucket used by the infrastructure CI/CD pipeline
# to transfer files to the private Admin EC2 instance.
#
# High-level flow:
#
#   GitHub Actions
#         |
#         | upload bootstrap/Ansible files
#         v
#   S3 transfer bucket
#         |
#         | Admin EC2 downloads files
#         v
#   Admin EC2
#         |
#         v
#   Management EKS
#
# Nothing stored here is persistent application data.
# =============================================================

resource "aws_s3_bucket" "ansible_ssm_transfer" {
  # checkov:skip=CKV2_AWS_62:Temporary CI transfer objects do not require event-driven processing.
  # checkov:skip=CKV_AWS_144:Cross-region replication is unnecessary for temporary CI transfer files.
  # checkov:skip=CKV_AWS_21:Versioning is intentionally disabled because transfer files are temporary.
  # checkov:skip=CKV_AWS_145:SSE-S3 provides sufficient encryption for temporary infrastructure transfer files.

  bucket = "logbeacon-ansible-ssm-transfer"

  # The transfer files are disposable.
  #
  # During `terraform destroy`, Terraform can empty the bucket
  # before deleting it.
  force_destroy = true

  tags = merge(
    local.common_tags,
    {
      Name = "logbeacon-ansible-ssm-transfer"
    }
  )
}


# =============================================================
#             TRANSFER BUCKET PUBLIC ACCESS BLOCK
# =============================================================
#
# This bucket is strictly internal infrastructure storage.
# No public access is required.
# =============================================================

resource "aws_s3_bucket_public_access_block" "ansible_ssm_transfer" {
  bucket = aws_s3_bucket.ansible_ssm_transfer.id

  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}


# =============================================================
#                TRANSFER BUCKET ENCRYPTION
# =============================================================
#
# Explicitly enables SSE-S3 encryption.
#
# S3 encrypts uploaded transfer objects at rest using
# S3-managed encryption keys.
# =============================================================

resource "aws_s3_bucket_server_side_encryption_configuration" "ansible_ssm_transfer" {
  bucket = aws_s3_bucket.ansible_ssm_transfer.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}


# =============================================================
#                TRANSFER BUCKET VERSIONING
# =============================================================
#
# Versioning is intentionally disabled.
#
# These files are temporary CI/bootstrap files, so retaining
# historical versions would only create unnecessary storage.
# =============================================================

resource "aws_s3_bucket_versioning" "ansible_ssm_transfer" {
  bucket = aws_s3_bucket.ansible_ssm_transfer.id

  versioning_configuration {
    status = "Disabled"
  }
}


# =============================================================
#                TRANSFER BUCKET LIFECYCLE
# =============================================================
#
# Temporary transfer files should not remain in S3 indefinitely
# even when the infrastructure itself continues running.
#
# Objects are automatically removed after 1 day.
#
# Multipart uploads that were started but never completed are
# also cleaned up after 1 day.
# =============================================================

resource "aws_s3_bucket_lifecycle_configuration" "ansible_ssm_transfer" {
  bucket = aws_s3_bucket.ansible_ssm_transfer.id

  rule {
    id     = "expire-transfer-files"
    status = "Enabled"

    # Apply this lifecycle rule to every object.
    filter {}

    # Remove temporary transfer objects after one day.
    expiration {
      days = 1
    }

    # Prevent incomplete multipart uploads from accumulating.
    abort_incomplete_multipart_upload {
      days_after_initiation = 1
    }
  }
}


# =============================================================
#              ENABLE S3 SERVER ACCESS LOGGING
# =============================================================
#
# Records access made against the transfer bucket.
#
# Logs are delivered to:
#
#   s3://logbeacon-log-bucket/
#       ansible-ssm-transfer-logs/
#
# The bucket policy must exist before logging is enabled,
# otherwise S3 may not have permission to deliver the logs.
# =============================================================

resource "aws_s3_bucket_logging" "ansible_ssm_transfer_logging" {
  bucket = aws_s3_bucket.ansible_ssm_transfer.id

  target_bucket = aws_s3_bucket.log_bucket.id
  target_prefix = "ansible-ssm-transfer-logs/"

  depends_on = [
    aws_s3_bucket_policy.log_bucket_policy
  ]
}